### ISSUE TITLE
Delta load support

### ISSUE THREAD

**Issue by quintona** [CommBank/maestro#106]
At present we easily support direct loads, and with a little bespoke effort could support delta loads. However we will then land up with a wide range of brittle delta based implementations. We need to support delta loads as a first class load pattern and ensure all the good convention is in place there

**Comment by SamRoberts** [comment]
Could we bring the existing delta work done in `util.etl` into maestro?

I think the existing delta implementation makes sense when the provided data has no structure, but I would hope that many data sets offer some sort of monotonic field which could be used to provide a better implementation.

**Comment by stephanh** [comment]
Closing this since we support delta loads in util.etl.
