### ISSUE TITLE
Default partition functions should be more generic

### ISSUE THREAD

**Issue by stephanh** [CommBank/maestro#126]
We should have more generic default partition functions that can accept as input lists with more than the required files and can have custom separators.

E.g `Partition.byDate` should be able to handle extract_timestamp fields with values such as `yyyy/mm/dd/hh` or `yyyy-mm-dd`.

Alternatively, we should change extract_timestamp to be an actual timestamp, #127.

**Comment by SamRoberts** [comment]
The partition functions are more generic now.
