### ISSUE TITLE
Load ignores too much input

### ISSUE THREAD

**Issue by stephanh** [CommBank/maestro#147]
The Load command silently drops columns that exceeded the number of fields in the thrift struct.

The Tag.tag command will just force each input row to be the right length.

**Comment by stephanh** [comment]
I can fix this problem by either changing `case class Tag[A](run: List[String] => List[(String, Field[A, _])])` to something like `case class Tag[A](run: List[String] => String \/ List[(String, Field[A, _])])` and ensuring that the run method fails if the list is too short or long. This will have an impact on backwards compatibility. Probably not too much since I don't think anyone use it directly.

Or I can just add a check in `LoadEx.parseRows` to discover this error and handle it there.

Thoughts anyone?

**Comment by SamRoberts** [comment]
I was imagining the first method. Where reasonable, I would prefer to report errors at the point where they arise, not check for errors first and then rely on that check for the correctness of later steps. But I was assuming that users weren't using tag directly.

(Which is a good point? If some of these "internal" load types are in our api, maybe we should take them out?)

**Comment by vineethvarghese** [comment]
Changing the run on Tag seems the right way if possible.

**Comment by rowandavies** [comment]
@stephanh Maybe I've missed something, but I thought that in the existing `LoadEx.parseRows`, within the `Decode.decode` will already catch the situation of extra fields and hit the `case TooMuchInput =>`. 

But, I'd agree that the first solution is better.  Defining the tags for `StringPair` and `StringTriple` as infinite streams doesn't feel so natural.

**Comment by SamRoberts** [comment]
@rowandavies the current implementation of tag, created by our macros, zips the list of columns with the list of expected `Field`s, thereby truncating any extra columns before they are ever passed to decode.

**Comment by rowandavies** [comment]
Oh.  So then the maestro tests using `StringPairTag` aren't representative of production code.   Having run the tests, and seen the rows with extra columns get tagged as errors, I was mislead into thinking that was what would happen during actual loads.  So definitely something needs to be fixed here.

I don't object to the zip with an infinite stream, but I don't think this should be built into `StringPair` and `StringTriple`.  We could instead to add the infinite stream at the end when we do the zip via `++` or similar.  Or, we could make the errors explicit from Tag.tag.

**Comment by stephanh** [comment]
Agreed. I want to deal with this properly and want StringPair and StringTiple to be representative of what they should be like.

**Comment by stephanh** [comment]
Since no one spoke up about concerns with backwards compatibility and I don't think it will have a big impact I'm going to change the tag implementation.

**Comment by rowandavies** [comment]
Cool.  I'll modify `StringTriple` accordingly in #338, I guess the modification to `StringPair` instead belongs here in #147.
