### ISSUE TITLE
Compatibility Testing

### ISSUE THREAD

**Issue by quintona** [CommBank/maestro#18]
We need a full suite of compatibility tests working. We will be generating data using the following technologies:

* Scalding/cascading with Ebenezer and Maestro support
* Hive 

And consuming the data using:

* Scalding/cascading with Ebenezer and Maestro support
* Hive 
* Impala

Early indications are that there are compatibility issues, and longer term this needs to be in place and is critical. This project already exists: https://github.com/Parquet/parquet-compatibility, we would need to extend it or use it (haven't looked at the details) and ensure that cross product of the above combinations is properly covered.

**Comment by stephanh** [comment]
There is compatibility testing in ebenezer for reading and writing parquet files using Hive and Scalding (ebenezer).
