### ISSUE TITLE
Tooling around dependency version management

### ISSUE THREAD

**Issue by vineethvarghese** [CommBank/maestro#206]
There needs to be more rigour around managing a project's dependency. Right now, version issues are caught at deployment and are often difficult to debug. Given the manner in which transitive dependencies are pulled in by hadoop, project should be explicit about what dependencies it wants in the assembly (atleast the hadoop dependencies). We could start with have a simple build plugin that analyzes a dependency graph and fails the build if it detects conflicts. What constitute a conflict should be customizable (like we don't care about minor version conflicts etc).

**Comment by SamRoberts** [comment]
Superseeded by #316
