### ISSUE TITLE
Ability to merge smaller files into a bigger file

### ISSUE THREAD

**Issue by anandsiva** [CommBank/maestro#259]
Some of the reference data or the source system sending delta files will have lots of smaller files. In the long run this could cause issue. We could do compaction as an optional post processing for certain feeds.

**Comment by SamRoberts** [comment]
I am starting work on this now. Current tasks:
 1. Collaborating with @sujeshce to find technologies and/or code is producing all the small files.
 2. Can we modify these to produce less small files initially? E.g. by configuring them differently, or by creating wrappers around the classes doing the reading and writing.
 3. Are there cases where we can't make the initial jobs produce less files, but can merge in a post-processing step? E.g. an Execution function which writes the results of these jobs to a temporary directory structure, before merging the output and placing it in the destination directory structure.
 4. Are there cases where we can't make the initial jobs produce less files, and we can't easily do merging as a post-processing step? E.g. Hive tables. What we do in such situations is still an open question.

**Comment by SamRoberts** [comment]
Note that the `parquetjoiner` tool mentioned above is now available as a fork of herringbone here: https://github.com/CommBank/herringbone/

**Comment by stephanh** [comment]
@SamRoberts what is the latest state of this? Can it be closed based on the PR you did and parquetjoiner?

**Comment by SamRoberts** [comment]
I didn't close this because I don't have any reason to believe that my load fix was enough to solve the broader problems of the tools we use producing small files.

I imagine that, at the very least, we should be investigating hive files too. But it's really not up to me: we should be getting feedback from the platform team as to whether our loads are still producing too many small files or not.

**Comment by SamRoberts** [comment]
I spoke to the platform team about this, and am closing the issue for now. Early testing showed it made an improvement. If there are loads it is not working for, we can raise a new issue.
