### ISSUE TITLE
proper integration of Guard functions with Execution

### ISSUE THREAD

**Issue by SamRoberts** [CommBank/maestro#285]
At the moment the Guard functions use dummy Configurations to create and use a hadoop filesystem instance. Instead, we should expose these functions as `Hdfs` or `Execution` actions, so they use the provided configuration and are consistent with the rest of the maestro API.

**Comment by SamRoberts** [comment]
Note that although the Guard functions are less necessary now that we can get the list of uploaded files from upload or sqoopImport, we still need them if we write a job that deals with files that are already on HDFS.

**Comment by rowandavies** [comment]
In the PR review for etl.ebilling-pricinginformation today, Guard.createFlagFile was used via:
`Execution.from(createFlagFile(conf.inputs))`
There was a PR comment that createFlagFile use the HDFS monad would be better.

**Comment by toddmowen** [comment]
Based on the comment by @rowandavies, I will convert to `Hdfs` unless somebody has a reason to prefer `Execution`.

**Comment by rowandavies** [comment]
Hdfs seems appropriate, and there's an explicit coercion from this to `Execution`, namely `RichExecution.fromHdfs` aka `hdfs`.
