### ISSUE TITLE
Should maestro api package expose Hdfs and Hive

### ISSUE THREAD

**Issue by stephanh** [CommBank/maestro#287]
Should the Maestro API package expose Hdfs from permafrost and Hive from Ebenezer. Also should we include the Hdfs string implicits as part of `Mastro._`.

**Comment by SamRoberts** [comment]
The rationale for _not_ exposing scalding's Execution type from the Maestro API was that user's would commonly import other items from scalding, and commonly do so via wildcard imports, and we didn't want them to have to juggle the same type coming from multiple locations.

As these items have their own dedicated namespace in their respective projects, I don't see that objection applying here, and I think it makes the import list considerably simpler. I am in favor of this.
