### ISSUE TITLE
Test intermittently fail

### ISSUE THREAD

**Issue by stephanh** [CommBank/maestro#303]
Our tests seem to be intermittently failing all of the sudden. So far ViewExecutionSpec and CustomerExecutionSpec have failed.

**Comment by SamRoberts** [comment]
The zip test in ViewExecutionSpec has always intermittently failed. CustomerExecutionSpec is new to me though.

**Comment by SamRoberts** [comment]
CustomerExecutionSpec zips two viewHive statements as well, so it may well be the same issue and I just haven't noticed it before.

**Comment by stephanh** [comment]
I haven't encountered this issue recently with the changes we made as part of the CDH5 upgrade.

**Comment by stephanh** [comment]
Doesn't seem to be happening anymore so I will close it.
