### ISSUE TITLE
Empty daily Partition to be created during loading for no record in files

### ISSUE THREAD

**Issue by jonjuscorpion666** [CommBank/maestro#315]
Needs empty partition to be created when files arrived without any data .

Scenario : currently no partitions with be created  after loading because of  2 reason 1) No Files arrived for loading 2) No records in Files .

We would like to create an empty partition for empty input files . So that Downstream transformations will be easier . 
Happy to discuss more abt use case.

**Comment by stephanh** [comment]
Why do you need the empty partition?

**Comment by jamindaw** [comment]
This a problem of how extracts are triggered and designed. We need to fix that problem.

**Comment by stephanh** [comment]
Closing this since this should now be handled by utilising the control table.
