### ISSUE TITLE
Fix maestro dependency issues

### ISSUE THREAD

**Issue by SamRoberts** [CommBank/maestro#316]
Maestro, and the other CommBank projects we rely on, like permafrost and ebenezer, have a number of issues regarding dependency management:

 1. The projects don't always agree on the version of a library to use
 2. The projects don't always use the same version of a library as the version supplied in the hadoop classpath
 3. When packaging the maestro assembly, when conflicting versions of a class are found, we resolve these conflicts by taking the first class in the classpath, rather than resolving the conflict sensibly.
 4. When packaging the maestro assembly, we include libraries that are part of the hadoop classpath.
 5. When packaging the maestro assembly, we include some libraries that may be required for other steps (e.g. testing or macros) but are not required at run-time (e.g. scala-compiler: I believe this is not required at runtime).

We need to:
 1. Ensure we are not depending on any libraries we do not need.
 2. As much as possible, ensure our projects all agree on the library version to use.
 3. As much as possible, ensure our projects use the library versions supplied in the Hadoop classpath.
 4. As much as possible, we should be excluding alternate versions of hadoop classpath libraries from any dependencies we have which rely on a different version of the library to the one on our cluster. We should ensure we compile and test with the versions on our cluster.
 5. Ideally, configure sbt to be make it an error if it finds separate versions of the same class while creating the assembly, with explicit overrides for cases where we can't avoid this. If this is not possible, we should at least ensure we are packaging the newest version of a class.
 6. Properly mark library in the hadoop classpath as provided. Make sure we have covered all the places where that jar is added to the final classpath, and confirm the jars are not being added to the assembly.
 7. Limit the scope of the dependencies so that we are not including any jars in the final assembly that might only be required for testing, or for running macros, etc. Confirm these jars are not being added to the assembly.
 8. Remove the temporary etl-plugin hack to strip jars from the final assembly

**Comment by stephanh** [comment]
This is linked to:
* https://github.com/CommBank/uniform/issues/31
* https://github.com/CommBank/uniform/issues/30
* https://github.com/CommBank/uniform/issues/28
* https://github.com/CommBank/uniform/issues/27

**Comment by SamRoberts** [comment]
1. **The projects don't always agree on the version of a library to use**

   Use strict ivy conflict management.

   Solutions, from preferred to least preferred. If it is hadoop classpath jar, pin the version, regardless of what other solution we may or may not follow.

   1. If possible, adjust version we depend on to remove conflict. (E.g., our version of guava is too new iirc)
   2. If on hadoop classpath, use dependencyOverride to pin version to hadoop cp. The pinning logic should be a function in uniform.
   3. If one jar is more "central" then the other, use it's version, and exclude it from other jars. Consider putting these deps in uniform together.
   4. Do whatever else seems to make sense in the situation!

2. **The projects don't always use the same version of a library as the version supplied in the hadoop classpath**

   See above

3. **When packaging the maestro assembly, when conflicting versions of a class are found, we resolve these conflicts by taking the first class in the classpath, rather than resolving the conflict sensibly.**

   Haven't investigated this yet

4. **When packaging the maestro assembly, we include libraries that are part of the hadoop classpath.**

   Use etl project to investigate what jars we are including in distro, and add provided annotations as required

5. **When packaging the maestro assembly, we include some libraries that may be required for other steps (e.g. testing or macros) but are not required at run-time (e.g. scala-compiler: I believe this is not required at runtime).**

   I think we can use provided annotations for this, but need to check.

**Comment by stephanh** [comment]
:+1:

I would suggest working with the lowest level of libraries and working your way up so that at every step you trim it down and then it should hopefully be less of jungle when you get to the load itself.

**Comment by SamRoberts** [comment]
makes sense. I was going to start with maestro, but parlour would probably be more sensible

**Comment by stephanh** [comment]
I was thinking omnitool or permafrost.

**Comment by SamRoberts** [comment]
I think another appropriate set of libraries to pin with dependency overrides is the scala-library and related jars (pin to `scalaVersion`, rather then some other 2.10 version).

**Comment by SamRoberts** [comment]
interestingly, omnitool has no conflicts, although I expect that it will cause conflicts later when I do maestro. But I will handle those conflicts then.

**Comment by SamRoberts** [comment]
Same story for permafrost. We're only going to start seeing those conflicts as we integrate them into higher level libraries.

**Comment by SamRoberts** [comment]
Here's an interesting dependency: libthrift. We depend on libthrift in a number of ways:

 - Version 0.9.0-cdh5-2 through hive-exec, provided when the user calls uniform's `depend.hive`.
 - Version 0.6.1 through bijection-scrooge, provided when the user calls uniform's `depend.scrooge`.
 - Version 0.7.0 through parquet-cascading. parquet-cascading is provided on the hadoop classpath, so this version of libthrift gets marked as provided too, but it is not on the hadoop classpath as far as I can see.

Different projects depend on different combinations of the above jars, so you can't single one jar our as the "source of truth" and exclude libthrift from the rest. I didn't want to use dependencyOverrides for libraries which are provided by our dependencies, but I am not sure what else to do in situations like this.

I am also concerned that parquet-cascading does not appear to include all of it's dependencies in the hadoop-classpath.

**Comment by SamRoberts** [comment]
Need to remember to ensure there is only one canonical place where parquet-cascading is defined and introduced. At the moment, parquet-cascading is defined in uniform, and also our private repos util.etl, and etl-plugin.

**Comment by stephanh** [comment]
@SamRoberts can this be closed?

**Comment by SamRoberts** [comment]
Have done steps 1-6 in the original comment, step 7 is "wontfix" for now, but I need to create an issue for that before closing this one, and step 8 still needs to be done (not removing the whole hack, but reducing it's scope to just the scala-compiler jar).

I need to go now, but I'll be doing those final bits and pieces first thing tomorrow I expect.

**Comment by SamRoberts** [comment]
I have created the issue for step 7, and have a pull request to remove the temporary jar hack from etl-plugin, so I am closing this now.
