### ISSUE TITLE
Default Hive Database names Needs to change in maestro

### ISSUE THREAD

**Issue by jonjuscorpion666** [CommBank/maestro#318]
Please change Default database from ${source}_${domain } to  s"${dbRawPrefix}_${source}_${domain}". As normally we have PR ,PS  or DR,DS or TR,TS as as db raw prefix

**Comment by jonjuscorpion666** [comment]
same applicable for hiveTable and PartitionedHiveTable Also

**Comment by jonjuscorpion666** [comment]
Also we need to add  dbRawPrefix  as standard command line argument inside maestro

**Comment by stephanh** [comment]
I think this was done by @jithinjohn as part of #360. @jonjuscorpion666 can you check if there is anything still missing or close the ticket?

**Comment by jonjuscorpion666** [comment]
@stephanh #360 looks fine .you can close the ticket
