### ISSUE TITLE
Parse Header and Trailer Records

### ISSUE THREAD

**Issue by jamindaw** [CommBank/maestro#32]

**Comment by jamindaw** [comment]
Based on recommendation from BICD/PWC, we need to provide load assurance on the basis of the content of the Header and Trailer record.

Requirement is to;
1. Enable the developer to parse a header/trailer record based on a definition of the structure.
2. The developer can validate the load / extract of a file based on the values in the header/trailer record.

N.B. This solution needs to work irrespective of the size of the input file

An example structure of the trailer record is;
H|<File Name>|<File Date>
T|<Row Count>|<Field>|<Checksum Value>

**Comment by jamindaw** [comment]
For home loan load, the value is a sum of absolute values of the field identified in the trailer.

**Comment by lijessje** [comment]
What is the development status for this task now? 
When can we expect this utility available to use (starting from HLS load)

**Comment by SamRoberts** [comment]
@lijessje this has been completed, see the change in #351 for details (or ask me)
