### ISSUE TITLE
Adding import au.com.cba.omnia.etl.util.SimpleMaestroJob in Maestro Api

### ISSUE THREAD

**Issue by jonjuscorpion666** [CommBank/maestro#324]
I think its better to add au.com.cba.omnia.etl.util.SimpleMaestroJob  in Maestro Api So that we need not  have to explicitly import same. I am not sure is right way  to add Util api inside Maestro API.

**Comment by quintona** [comment]
That surely can't be right, do we already have project level dependency in that direction?

**Comment by SamRoberts** [comment]
No, we do not. If we incorporated `SimpleMaestroJob` into maestro, we would take the code itself into maestro, one way or another.

**Comment by quintona** [comment]
whats wrong with the explicit import? there are many ways of making that better

**Comment by SamRoberts** [comment]
`SimpleMaestroJob` simply provides a default for one of the methods in a `MaestroJob` trait that Maestro provides.

To my mind, the most important question is whether that default behavior is a sensible thing to include in Maestro or not. I am not very worried about explicit importing `SimpleMaestroJob`, but I am slightly concerned that our users have elected to replace the `MaestroJob` trait we supply with one which supplies additional non-CBA-specific default behavior. If that additional non-CBA-specific behavior is good, maybe we should incorporate it into `MaestroJob`? If it is bad, why not fight back against using `SimpleMaestroJob`?

**Comment by SamRoberts** [comment]
I would also be interested in finding out why people create `SimpleMaestroJob` instead of issuing a maestro pull request to add that behavior to `MaestroJob`.

**Comment by stephanh** [comment]
It exists because I saw lots of loads that were creat a trait that was identical to `SimpleMaestroJob`.

The reason it is in `util.etl` instead of Maestro is that I'm not happy with that approach and I, therefore, don't want it in Maestro.

However, due to our skills profile we also lack the maturity at this stage to deal with the issue properly.
