### ISSUE TITLE
Upload for multiple sequence files into single location

### ISSUE THREAD

**Issue by maxmithun** [CommBank/maestro#325]
Unable to upload when multiple sequence of files comes for a single date. When the first sequence is  uploaded the INGESTION_COMPLETE flag is set and the upload of next sequence fails

**Comment by stephanh** [comment]
@SamRoberts can you please take a look at this.

**Comment by SamRoberts** [comment]
It's a known issue. Do you want to spend time on a fix now?

**Comment by stephanh** [comment]
Can you discuss with @maxmithun to either fix it or come up with a work around. It is affecting the remediation work for CDH5.

**Comment by SamRoberts** [comment]
Sure

**Comment by SamRoberts** [comment]
a fix for this has been merged into master
