### ISSUE TITLE
Handling strings within double quotes for file based loads

### ISSUE THREAD

**Issue by SajeevAr** [CommBank/maestro#337]
For file based loads, there is a use case where only text fields in a row are enclosed in double quotes and all other integer/decimal fields do not have any double quotes in a comma delimited file.

Sample row in input file:
"ABC001","232",45,0.00,"Sample Data","Sample Data (String,Title)","8/298/78899",1,"26/11/2014",1,"",""

Need to parse data as follows : 
1. All data values within double quotes need to be loaded as such without any alteration. (It may even contain the delimiter value itself. For example, "Sample Data (String,Title)")
2. Need to load integer and decimal values in the data file which do not contain any double quotes.

**Comment by SamRoberts** [comment]
perhaps we should investigate it a proper csv parsing library is available which meets our needs

**Comment by rowandavies** [comment]
@SajeevAr Do we need to allow quoted text fields that contain quoted double quotes like `"A ""quoted"" word"` (following the csv rule of using "" for " within quotes)?  (This should be easy.)
Similarly, should we allow them to include newline characters?  (This might not be easy.)

**Comment by rowandavies** [comment]
@SajeevAr @anandsiva _Summarizing our discussion yesterday:_ there's no current need to deal with newline characters in quoted fields.  Should the need come up later, most likely it would be dealt with separately via preprocessing.

Also, I'm not assigning this to myself now, I have other issues I need to work on currently.  I'd gladly mentor if you want to work on this feature now.

**Comment by SamRoberts** [comment]
I am thinking of changing the delimited splitter to use http://opencsv.sourceforge.net/apidocs/com/opencsv/CSVParser.html#parseLine(java.lang.String) under the hood. If there are any concerns about backwards compatibility, could also create a new `csv` splitter instead.

**Comment by SamRoberts** [comment]
#352 provided a new splitter: `Splitter.csv`, which can be used with quoted strings.
