### ISSUE TITLE
Automapper should accumulate errors

### ISSUE THREAD

**Issue by shmookey** [CommBank/maestro#374]
Currently compile throw an exception and terminate the mapper process. Ideally we should collect all mapping errors and display them at once.

**Comment by rowandavies** [comment]
@triggerNZ Is there a pull request for your changes?

**Comment by triggerNZ** [comment]
Yes, https://github.com/CommBank/maestro/pull/396. It was accepted and merged, but this issue wasn't closed.

**Comment by vineethvarghese** [comment]
@triggerNZ Thanks for cleaning this up. It might be better if we mention the PR while closing i.e. if it is not already mentioned in the issue.

**Comment by triggerNZ** [comment]
Fixed by PR #396
