### ISSUE TITLE
Add Sqoop export from pipe

### ISSUE THREAD

**Issue by stephanh** [CommBank/maestro#377]
Add functionality so that we can do a sqoop export from a scalding pipe.

This requires writing the data out in a way that sqoop can parse (probably csv)

**Comment by shmookey** [comment]
Implemented in https://github.com/CommBank/maestro/pull/380

**Comment by stephanh** [comment]
Has anyone used this new functionality? Can you please make sure that someone from loads tries it in one of their loads and it works for them.

**Comment by vineethvarghese** [comment]
@shmookey @aswinrkrishnan wanted to use this. Maybe you could check with him or @jonjuscorpion666 .

**Comment by jonjuscorpion666** [comment]
@shmookey . We have a similar requirement,will test and keep you post .

**Comment by aswinrkrishnan** [comment]
@shmookey All the fields exported is "null" at the teradata side. May be its due to the "Encode.encode(nul, _)", I tried exporting without this and it worked. Could you please look into this..?

**Comment by shmookey** [comment]
I've had reports of this working now. A separate but related issue is that users calling sqoopExport with a type variable must add the Encode typeclass to the caller - it is not sufficient for sqoopExport to do this itself. Unfortunately, the consequences for failing to do so are not visible until runtime.

**Comment by stephanh** [comment]
This has actually been fixed as part of 1cb61aa and 75c9521. If you still have that problem in Maestro version after 17/7 please reopen this issue or create a new one.

There is a problem for macros where they don't respect the type annotations (i.e. that something needs to be a ThriftStruct). We did some refactoring and as part of that introduced checks to prevent that from happening.
