### ISSUE TITLE
ViewExecution.viewHive doesn't overwrite the partition as expected.

### ISSUE THREAD

**Issue by vineethMM** [CommBank/maestro#382]
the call to 'viewHive(hiveTbale, inputPipe, append = false)' doesn’t fully overwrite the partition, instead it overwrites the files in partitions which are of the same name.Due to this some files remain in the partition and result in duplicate/unwanted  records. Currently all GDW loads using this functionality are affected by this issue.

**Comment by stephanh** [comment]
@vineethMM as a work around to this for the time being can you just use the `Hdfs.delete` from the Hdfs monad to delete the target folder before you write to it.

**Comment by stephanh** [comment]
@kfish I figured out how to solve the problem.

You will need to write all the data to a temporary location. Enumerate all the sub directories, delete the corresponding existing sub directories in the destination and then copy the new ones across.

**Comment by stephanh** [comment]
You will also need to to update the hive partitions to ensure that the new files are picked up.

**Comment by stephanh** [comment]
@vineethMM we will try and address this next sprint. However, this is not a simple issue and might take a while to solve.

**Comment by vineethMM** [comment]
@stephanh thanks for the update. We can have the work around for scenarios where, we know the partitions that are going to be affected,. Else its difficult to track the duplicates/ unwanted rows.

**Comment by SajeevAr** [comment]
When there is difference in the number of parquet files generated in the partition after overwrite, there can be some issues as described in the following scenarios. Now the new files will overwrite the previous files if it has the same file name. The current fix works fine only if the parquet files are created with unique file names inside a partition.

Case 1:
The partition initially contains two files - part-00000-00000-m-00000.parquet and part-00001-00000-m-00001.parquet. The overwrite job with a small data set may create only one new file - part-00000-00000-m-00000.parquet, by overwriting the previous file which has the same name. In this case, the obsolete file part-00001-00000-m-00001.parquet will still remain in the partition and will not be deleted as per the current approach.

Case 2:
The partition initially contains only one file - part-00000-00000-m-00000.parquet and the overwrite job with a bigger data set can generate two new files - part-00000-00000-m-00000.parquet and part-00001-00000-m-00001.parquet. In this case, the new part-00000-00000-m-00000.parquet will also get deleted as per the current approach.

I think generating a unique file name can resolve this issue. Changing Line 107 in HiveTable.scala to `counters <- write(externalPath).withSubConfig(modifyConfig)` should fix this.
