### ISSUE TITLE
Compilation error while applying transformation using automap

### ISSUE THREAD

**Issue by aswinr7** [CommBank/maestro#383]
automap macro is not getting resolved and getting compilation errors on the output thrift fields when applying transformation.

**Comment by shmookey** [comment]
Macro annotations require macro paradise to be enabled. For ETL projects, you can do this by adding the following to the end of the `etl.project` line in `build.sbt`:

` ++ Seq(addCompilerPlugin("org.scalamacros" % "paradise" % "2.0.1" cross CrossVersion.full)0)`

**Comment by quintona** [comment]
Do we want this line in all elt.* projects?

**Comment by stephanh** [comment]
The transformation macro is a core feature of Maestro so we want every project to be able to use it by default.

I would have preferred that the macro doesn't require having macro paradise everywhere but it's too late for that.
