### ISSUE TITLE
Simplify MaestroHdfs tests

### ISSUE THREAD

**Issue by toddmowen** [CommBank/maestro#386]
I have a patch ready, but it requires latest version of permafrost, therefore waiting on Scala 2.11 upgrade to Maestro.

(Technical details: CommBank/permafrost#11 allows us to assume that file listings are ordered, therefore `MaestroHdfsSpec` can be rewritten more concisely without the use of `containTheSameElementsAs`).

**Comment by stephanh** [comment]
@toddmowen do you still have that patch?
