### ISSUE TITLE
Add driven plugin

### ISSUE THREAD

**Issue by gavinwhyte** [CommBank/maestro#416]
Please add the relevant code to allow maestro to communicate with the Driven Server.

Sample code for Driven Plugin 
https://gist.github.com/gavinwhyte/a28cbd3e1f3567bab1a6

https://gist.github.com/gavinwhyte/8fe13ab450410d474494

Installation guide for plugin.

http://docs.cascading.io/driven/1.0/getting-started/

**Comment by quintona** [comment]
I am not sure this would go into maestro. Would it not go into etl. et al?

**Comment by gavinwhyte** [comment]
Good point, I will discuss with Vineeth, as per conversation with Stephan, he preferred it if I posted the sample code and config as a maestro github issue.

**Comment by rowandavies** [comment]
I agree, probably it will go into the individual `etl` jobs, perhaps via some tiny method/function in `util.etl`.

**Comment by vineethvarghese** [comment]
We don't have a nice way to raise an issue against an etl projects.

**Comment by vineethvarghese** [comment]
I forgot that util.etl is on github now, so this could go there.

**Comment by stephanh** [comment]
Raised on etl-util as https://github.com/CommBank/util.etl/issues/15
