### ISSUE TITLE
Split Execution "helpers" into separate project

### ISSUE THREAD

**Issue by SamRoberts** [CommBank/maestro#418]
In the realtime team we would like to make use of all the helper functionality you have in maestro for using executions, but we don't have any use for the maestro job or task apis. It would be nice if we could split the RichExecution functionality into a separate project, so we could depend on it without bringing in all of maestro.

We would be happy to do the initial work, but it would still require you to pay ongoing costs of maintaining code spread out over an additional repo (or an additional project in the maestro repo?).

Would you be interested in a PR that split this functionality out?

**Comment by SamRoberts** [comment]
The automapper macro would be pretty helpful too, come to think of it

**Comment by SamRoberts** [comment]
... aaand HiveTable ...

(if this keeps going we might as well just depend on maestro!)

**Comment by SamRoberts** [comment]
Although if you were to split out the execution helpers, than Partition and HiveTable might belong in ebenezer, and ebenezer could depend on just the execution helper lib?

**Comment by vineethvarghese** [comment]
How urgent is this and do you have a complete picture on what you want?

**Comment by SamRoberts** [comment]
Not urgent, and I'm not presenting a hard set of requirements, just hoping to set off a discussion.

**Comment by SamRoberts** [comment]
Currently I have copied a simplified and limited version of `bracket` (hardcoded to our specific use-case) and `fromHdfs` into our code, and I am about to write some map function from one thrift struct to another that would be a perfect use case for the automap macro.

**Comment by stephanh** [comment]
@SamRoberts why don't you want to depend on Maestro?

**Comment by SamRoberts** [comment]
@stephanh no practical reason, really. It's just that the "core purpose" for the maestro library to exist (the standard load patterns used in datahub) are not relevant to us. The functionality I want makes executions, hive, thrift, etc, easier to use in general. It isn't maestro specific in any way IMO.

That said, I'm not dogmatic about it.

**Comment by stephanh** [comment]
@SamRoberts we have set up our projects subprojects more around external dependencies to avoid pulling in dependencies you don't need such as Scalding, Parquet, etc so far. I think in the short term you should just depend on Maestro.

`RichExecution` needs to depend on `Hive` from ebenezer, `Hdfs` from permafrost and, obviously, Scalding so it pretty much pulls in all possible dependencies anyway so there is limited use in splitting it out.

If we have time I would like to look at moving some of the macro stuff in Humbug.

**Comment by SamRoberts** [comment]
@stephanh no worries, we can do that. I'll close this.
