### ISSUE TITLE
Automap throwing error with single field transformation

### ISSUE THREAD

**Issue by sabarinathks** [CommBank/maestro#428]
Automap is throwing "Could not resolve FieldName" error with single field transformation:

1) When used for mapping a single field from source thrift to destination thrift. Destination thrift is same  as source thrift except an additional field at the end.

 @automap  def fooTransform(f: foobar): foobarTransformed = {
    foo := f.foobar
  }  where foo is the last field in destination thrift and foobar is the last field in source thrift

Error that is throwing is ,

Could not resolve `foo`
@automap  def fooTransform(f: foobar): foobarTransformed = {
   ^
not found: value foo
foo := f.foobar
   ^

2) When tried with additional identity mapping it is working fine.

@automap  def fooTransform(f: foobar): foobarTransformed = {
    foo := f.foobar
    foobar1 := f.foobar1
  }

**Comment by stephanh** [comment]
This seems to actually be caused by the Automap macro not handling correctly any transformations with just one rule.
