### ISSUE TITLE
Links to source code from scaladoc are broken

### ISSUE THREAD

**Issue by stephanh** [CommBank/maestro#443]
We seem to be breaking the link to source code from scaladoc https://github.com/CommBank/maestro/tree/Dirty(bc9f5fa5e0d8ef87f1a2bc138859f1c9a46888de)//maestro-scalding/src/main/scala/au/com/cba/omnia/maestro/task/LoadExecution.scala

**Comment by vineethvarghese** [comment]
I believe Rowan had already filed an issue about this.

-V

**Comment by stephanh** [comment]
You are right. I did a search on my phone and couldn't find anything. However, it turns out this is a duplicate of #419.
