### ISSUE TITLE
Large number of partitions causes viewHive to fail

### ISSUE THREAD

**Issue by shmookey** [CommBank/maestro#462]
viewHive fails for tables containing very large numbers (tens of thousands) of partitions. Currently new partitions are registered by the metastore automatically by issuing the memory-intensive `MSCK REPAIR` command to Hive, which crashes when the partition count is too high, even for small differentials.

Workaround: register created partitions manually with the metastore in smaller batches.

**Comment by rowandavies** [comment]
See https://github.com/CommBank/maestro/issues/459
