### ISSUE TITLE
The ability to handle multiple smaller inbound datasets

### ISSUE THREAD

**Issue by anandsiva** [CommBank/maestro#47]

**Comment by stephanh** [comment]
@anandsiva can you please provide some more detail and how it relates to #259.

**Comment by SamRoberts** [comment]
@stephanh @anandsiva this seems like it should be closed now?

**Comment by anandsiva** [comment]
This is related to platform where lots of small files are created due to the fact that some of the inbound files are relatively small. And there are lots of files with few Kb on a day to day basis received from the source system. This could be merged with #259

**Comment by SamRoberts** [comment]
Sure. I will close this now in favor of #259, which is still open pending feedback about whether we are still creating lots of small files or not.
