### ISSUE TITLE
Ability to load files with  file-timestamp in different timezones.

### ISSUE THREAD

**Issue by AnnTomie** [CommBank/maestro#481]
*Background:*
SAP generates filenames with UTC as default timezone. During daylight saving, files
 were generated with timestamp ```2015-10-04-02%```
 which was invalid in AEST. While setting this timestamp to joda DateTime object, upload step failed as AEST is considered as the default timezone. From the execution we use a regex pattern to identify files from inbound location and if regex matches, it extracts the timestamp from the filename. When joda accepts this timestamp in default timezone, we end up in failure scenarios during daylight savings. Next
 daylight saving date is  Apr 3, 2016 .
*Related issue* : https://github.com/CommBank/datahub/issues/132

**Feature:**
Ability to indicate the timezone associated with the filename whenever it is other than AEST format. Currently, Maestro Load (including Upload,viewHive steps ) expects file timestamp in AEST format by default.

**Comment by rowandavies** [comment]
This is also related to issue #204

**Comment by rowandavies** [comment]
Resolved by #483

**Comment by SajeevAr** [comment]
The current timezone addition provides the ability to specify timezone associated with a file during upload and hence fixes the issues in upload step. However, apart from upload, the default AET timezone was assumed in the following instances as well, which may lead to job failures.

1. Methods `byYear`, `byMonth`, `byDay`, `byHour`, `byDate` etc. in `Partition.scala` will parse the timestamp in partition field based on a given format. So viewHive step will fail if the timestamp is invalid in default timezone.
2. `isDate` method in `Validator.scala` will fail if timestamp in validator field is invalid in default timezone.
3. `now` method in `TimeSource.scala` also use the default timezone to generate `Timesource`. It doesn't cause a job failure, but it restricts from creating timesource in a particular timezone.

To fix these issues, we need to add the capability to specify the required timezone for these scenarios as well.

**Comment by andynygard** [comment]
@SajeevAr Could you please open a new issue so that we have visibility of this?
