### ISSUE TITLE
PartitionedHiveTable could be generalised to typed pipes with thrift extractors.

### ISSUE THREAD

**Issue by rowandavies** [CommBank/maestro#488]
@knservis, @vineethMM & others have a use case for `au.com.cba.omnia.maestro.hive.PartitionedHiveTable.writeExecution` that currently doesn't fit because it requires accepting a typed pipe of pairs of thrift structures and associated partitions (dates as `(String, String, String)`).   Converting these to a single thrift beforehand would be inconvenient and need to be done for multiple clients, so instead the plan is to generalise `PartitionedHiveTable.writeExecution` (or add a generalised version) to allow taking any typed pipe from which the appropriate thrift and partition information can be extracted.

It looks like this could have been done by extending the trait `HiveTable` if this wasn't sealed, and maybe we can unseal it regardless.  But I think the generalisation naturally fits with the current `PartitionedHiveTable`.

@vineethvarghese I think this will go smoothly, but do you see any issue with @knservis and @vineethMM implementing this generalisation?

**Comment by vineethvarghese** [comment]
@rowandavies No. Sorry just catching up on some issues.

**Comment by rowandavies** [comment]
No problem, we discussed it in person.  This should have been linked to #493 since that resolves this.

**Comment by vineethvarghese** [comment]
Close this maybe?
