### ISSUE TITLE
Automate new ETL project initiation

### ISSUE THREAD

**Issue by JeremyMarshall** [CommBank/maestro#501]
To build stash and teamcity

Instructions here http://knowit.cba/display/OMNIA/ETL+Project+Repo+Creation

Possibly dockerise it and initiate it with teamcity using a parameter for the project name

**Comment by rowandavies** [comment]
We already have automation for this in the giter8 template that generates the initial code for new ETL projects, stash repos and the associated CI in teamcity, but it's clearly in need of an update.

We could move away from giter8 in the process, but only if there's a clear reason to do so.  One alternative could be to do offline code generation via scala macros, as per: http://docs.scala-lang.org/overviews/quasiquotes/usecases#offline-code-generation

Also, we should look at whether it makes sense to combine what we have in the giter8 template with other pre-build code generation including the BICD generator and plans for similar generators for Bankwest and future projects.
